# basic options
title: Title
author: Graham Mc
email: email@domain.com
description: Personal Jekyll site
twitter_username: mcfroob
github_username:  pekoto

# Build settings
markdown: kramdown
theme: minima
